apiVersion: v1
kind: Service
metadata:
  namespace: 2048-application
  name: 2048-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    appname: app-2048
